### ISSUE TITLE
Readme figure

### ISSUE THREAD

**Issue by azev77** [pkofod/QuantileRegressions.jl#44]
Hi and thanks for this package!

In the readme, a figure plots 
1. quantile regression estimates along w/ confidence intervals
2. OLS regression estimates w/o confidence intervals
Is it possible to add confidence intervals to the OLS estimates as well?
![image](https://user-images.githubusercontent.com/7883904/86438571-db816380-bcd4-11ea-878e-7120aa9d6c29.png)

**Comment by azev77** [comment]
See: https://github.com/pkofod/QuantileRegressions.jl/pull/45

**Comment by pkofod** [comment]
Fixed in #45
