### ISSUE TITLE
update compatibility with current StatsModels

### ISSUE THREAD

**Issue by luboshanus** [pkofod/QuantileRegressions.jl#64]
Hi,

would it be possible to update compatibility with current packages used by QuantileRegressions?
Adding QuantileRegressions downgrades StatsModels in julia v1.8.5.

```julia
  [c6596682] + QuantileRegressions v0.1.10
⌅ [3eaba693] ↓ StatsModels v0.7.1 ⇒ v0.6.33
```

Thanks.

Luboš

**Comment by ymer** [comment]
Seconded

**Comment by pkofod** [comment]
@devmotion helped us here :) registering as we speak
